### ISSUE TITLE
Tassomai Automation Update

### ISSUE THREAD

**Issue by JaBaDeeZ** [Gloryness/tassomai-automation#10]
The New Update for the Tassomai Automation has caused it to successfully terminate script without doing any questions, i have enabled "Finished when daily goal complete" but still finishes without doing any questions. I think the new update might of broke the automation, pls fix this. Thnx
![tassomai problem](https://user-images.githubusercontent.com/77434790/104566175-2ea17f00-5645-11eb-8c98-8afe79075dcd.JPG)

**Comment by Gloryness** [comment]
fixed it i think-
