### ISSUE TITLE
Question Delay

### ISSUE THREAD

**Issue by mrberald** [Gloryness/tassomai-automation#13]
At the moment there's no variation between the time taken to answer a question its always whatever its set to, this may seem suspicious to teachers. It would be good if we could set 2 custom times and an rng will decide on the time taken to answer the question between the two times you've set. Otherwise great bot its got me out of a lot of work lmao thanks

**Comment by Gloryness** [comment]
ooh yeah, thanks for the suggestion - might add it idk.
