### ISSUE TITLE
Recording results

### ISSUE THREAD

**Issue by realdeadbeef** [Gloryness/tassomai-automation#16]
Just an idea, but you could have it create a database on a server which collects all the correct answers so if the bot hasn't seen the question on my pc it could see if someone else has had that question and then not even have to guess

**Comment by Ribs8511** [comment]
It does that already im quite sure

**Comment by realdeadbeef** [comment]
From reading the docs it only records the answers it has completed. Not including other peoples

**Comment by realdeadbeef** [comment]
I was wrong, turns out it already does that XD
