### ISSUE TITLE
Cant Seem To Stop This Error Code

### ISSUE THREAD

**Issue by vSxolar04** [Gloryness/tassomai-automation#19]
Whenever i run the automation i get given this error code and the whole thing closes 
![image](https://user-images.githubusercontent.com/77799204/105385108-e23cdd00-5c0a-11eb-9ed1-17cf2a365502.png)

**Comment by Gloryness** [comment]
yeah.. i noticted this earlier, i'll try to work on it later.

**Comment by JaBaDeeZ** [comment]
@Gloryness the new update that you released recently includes the same error as the last version

**Comment by Gloryness** [comment]
try using v2021.01.25
