### ISSUE TITLE
Mutliple tassomai classes

### ISSUE THREAD

**Issue by drsoup** [Gloryness/tassomai-automation#2]
After joining a new class on tassomai, I have noticed the automation has an error starting
" Successfully updated local database by fetching the Public Answers Database!

Loading Firefox...
Successfully opened Firefox.

Loading URL: https://app.tassomai.com/dashboard/learner/quiz/1
Unable to log in to Tassomai.

------------------------------------------- "

**Comment by drsoup** [comment]
Successfully updated local database by fetching the Public Answers Database!

Loading Firefox...
Successfully opened Firefox.

Unable to login to Tassomai.

ERROR:root:Traceback (most recent call last):
  File "base\https\session.py", line 125, in start
  File "base\https\webdriver.py", line 34, in wait
  File "selenium\webdriver\support\wait.py", line 80, in until
selenium.common.exceptions.TimeoutException: Message:

**Comment by drsoup** [comment]
Before this happened, I was in love with the script. Best script I have ever seen, hope this can be fixed soon.

**Comment by Gloryness** [comment]
> 
> 
> Before this happened, I was in love with the script. Best script I have ever seen, hope this can be fixed soon.

Currently I'm looking through the code and it appears it's something to do with it not being able to find the class element `tass-start-quiz__button`. I can't really help you at the moment with the current information given.

Do you mind adding me on discord `Gloryness#4341` and I could try to debug the problem with you?

**Comment by Gloryness** [comment]
Since the GUI no longer uses selenium - this is no longer a problem.
