### ISSUE TITLE
Errors when running tassomai bot

### ISSUE THREAD

**Issue by Nuckerr** [Gloryness/tassomai-automation#22]
So when I run the automation, I get errors and it just crashes. I have tried updating and then deleting and reinstalling so I dont know whats up. I assume its something to do with `github-db` however I dont know how to reset it.

http://i.nucker.me/pmSMF.png

**Comment by Gloryness** [comment]
try using v2021.01.25

**Comment by Nuckerr** [comment]
Sorry but I can't find this on the relapses page: http://i.nucker.me/uKOKv.png

**Comment by Nuckerr** [comment]
I have found it, I still get all the errors

**Comment by Gloryness** [comment]
when i run it, i dont get any errors?

**Comment by Nuckerr** [comment]
These are my settings and the errors: http://i.nucker.me/bPmYr.png

**Comment by Nuckerr** [comment]
I feel as if I need to reset my database or something however I am not sure how to do that

**Comment by Gloryness** [comment]
Oh, the email or password must be incorrect then. If it successfully logs in, it would return a token for the program to use but however in the error it shows the token was not given so this clearly means the email or password is incorrect.

**Comment by Nuckerr** [comment]
Ok I will try and see

**Comment by Nuckerr** [comment]
I am 100% certain my details are right. I even changed my password and tried. I can login fine on tassomai.com

I did have this working fine until a few days ago. Is there any way I can reset the bot for me such as clearing all my data on the database as that might fix it?

**Comment by Nuckerr** [comment]
@Gloryness can you please re-open my issue, I still have it, its not my password, can you help me fix it

**Comment by Gloryness** [comment]
Yeah, its happening for me aswell now tho so i'm gonna fix it earlier if i can

**Comment by Nuckerr** [comment]
Alright thanks
