### ISSUE TITLE
Unable to select different subjects

### ISSUE THREAD

**Issue by MrrVeron** [Gloryness/tassomai-automation#28]
I'm only able to start quizzes for one subject at the moment. Is it possible to have a feature where you can select the class/subject you want to start the automation for?

**Comment by MrrVeron** [comment]
i do realise this was made for science, just asking if theres plans for things like maths and english in the future

**Comment by Gloryness** [comment]
yeah if i get around to it i'll think about adding it
im kinda busy with life atm so not right now XD

**Comment by MrrVeron** [comment]
fair enough thank you
