### ISSUE TITLE
pyqt5_tools version

### ISSUE THREAD

**Issue by NahinHalder** [Gloryness/tassomai-automation#30]
I have this issue. It says to download requirements, so I do pip3 install pyqt5_tools, but there are way too many versions. Can you specify which version to use? Or can you give me like a line that I can copypaste into terminal? Also, after I download all requirements, what do I do next?
![Screen Shot 2021-02-19 at 11 02 29](https://user-images.githubusercontent.com/31797662/108496481-03442c80-72a2-11eb-9e87-80248366e26f.png)

**Comment by NahinHalder** [comment]
This is my first time doing this, so if you don't mind, can you explain to me the steps to doing this? Do I go to code and then download or do I download the requirements then download it? I honestly am stuck. I was able to download the other requirements tho

**Comment by IamNotARobot1** [comment]
You don't have to download these things, that's only if you want to set it up manually. You can just download the exe version which is much easier unless you want to do the coding for it. You can download the exe by clicking the most recent release then clicking Tassomai.Automation.zip, which should install it.

**Comment by Gloryness** [comment]
> You don't have to download these things, that's only if you want to set it up manually. You can just download the exe version which is much easier unless you want to do the coding for it. You can download the exe by clicking the most recent release then clicking Tassomai.Automation.zip, which should install it. 

correct!
