### ISSUE TITLE
I have a problem downloading but i think its a problem on my end

### ISSUE THREAD

**Issue by BobKarma** [Gloryness/tassomai-automation#34]
i get this error
![image](https://user-images.githubusercontent.com/76540780/109140192-409e3380-7754-11eb-9549-280bba78cd6d.png)
i hope someone know a fix i have tried a cupel of times.  I turned off antivirus and even restarted my pc but it dose not work pls help

**Comment by Gloryness** [comment]
i'm not sure how to fix it, sorry
