### ISSUE TITLE
Constant crashes

### ISSUE THREAD

**Issue by james040404** [Gloryness/tassomai-automation#39]
Whenever I load up the program it establishes a connection, and then just shuts off after about a minute of doing nothing.

I've got the latest version, a relatively high-spec computer, and it used to work just fine until a few weeks ago. I've come back to it in the hope of it working again, but I'm still experiencing the same issues.

I'm opening it from the extracted folder, and running the program from there. I assume that's the correct thing to do? (It used to work, so I'm not quite sure what I'm doing wrong)

**Comment by Gloryness** [comment]
that's weird

**Comment by Gloryness** [comment]
ill test it later to see if it works for me !

**Comment by Gloryness** [comment]
it works fine for me btw so idk
