### ISSUE TITLE
Tassomai layout updated

### ISSUE THREAD

**Issue by BubblemintEDM** [Gloryness/tassomai-automation#41]
The new update seems to be interfering with things such as the amount of questions answered. Says 4430 even thought it only did like 40 questions (I think)

**Comment by Gloryness** [comment]
screenshot the problem, but for me its fine so thats why im confused

**Comment by BubblemintEDM** [comment]
![image](https://user-images.githubusercontent.com/69756370/113250821-21e20e00-92b9-11eb-9593-049f9ad916cb.png)

**Comment by BubblemintEDM** [comment]
as you can see the questions answered stat seems very off

**Comment by Gloryness** [comment]
OH yeah that just means the total amount of questions answered in the database lol

**Comment by Gloryness** [comment]
it's always been like that - i'll be sure to change it to something like "total questions answered in the database" in the future so it doesnt confuse people
