### ISSUE TITLE
Crashes on Startup

### ISSUE THREAD

**Issue by james040404** [Gloryness/tassomai-automation#42]
![image](https://user-images.githubusercontent.com/81260095/113837459-c6ff5980-9785-11eb-8901-afe77635c865.png)

Whenever I attempt to run the program, this shows up, and then it shortly closes. I'm certain my login details are correct, so I was wondering what else the problem might be?

**Comment by Gloryness** [comment]
I just tested it - it works fine for me. this clearly has something to do with the login credentials (nothing is wrong with the program itself) since the request resposne for the login was 'Unable to login with provided credentials'.
