### ISSUE TITLE
problem in the code

### ISSUE THREAD

**Issue by Hxxleykxrby** [Gloryness/tassomai-automation#43]
is says there is a problem in the code, i cant remember what line it is. but whenever i open up the software automation, it prints out some lines of code and says errors in line so and so. after this the app instantly closes down and you cant do anting. this keeps happening

**Comment by Gloryness** [comment]
Oh - can you send me a screenshot of the error? it might help

**Comment by Hxxleykxrby** [comment]
Hello this is what I get:
[Image]

Could you please help me get it working again. J have Uninstalled the programme for the time being.
Thanks


Sent from Samsung Mobile on O2
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Gloryness** [comment]
it doesnt show me the image? it just says "[Image]" and thats it.. try replying via github instead of gmail xD

**Comment by Hxxleykxrby** [comment]
Okay sorry about that

Sent from Samsung Mobile on O2
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Hxxleykxrby** [comment]
You have to download the image

Sent from Samsung Mobile on O2
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Gloryness** [comment]
i'm still confused . . it doesnt give me a link anywhere apart from https://aka.ms/AAb9ysg which brings me to https://www.microsoft.com/en-us/microsoft-365/outlook-mobile-for-android-and-ios which is pretty useless

**Comment by Hxxleykxrby** [comment]
don't worry I download the update and its all okay now thanks
________________________________
