### ISSUE TITLE
Possibility To Run In The Cloud?

### ISSUE THREAD

**Issue by server1-kali** [Gloryness/tassomai-automation#45]
Would there be a possibility to run tassomai-automation in the cloud somewhere - something like pythonanywhere or anything similar, or will there be a way to just have one python script to do your daily goals?

**Comment by server1-kali** [comment]
Essentially Yes, without having to open up the exe

**Comment by IamNotARobot1** [comment]
you're supposed to be able to use the task scheduler to run a .cmd file with commands at certain times every day but it doesnt work for me

**Comment by server1-kali** [comment]
Do you know where this .cmd file is

**Comment by IamNotARobot1** [comment]
Rename a .txt text file to .cmd. The commands are under "Tip" here: 
https://github.com/Gloryness/tassomai-automation

**Comment by server1-kali** [comment]
Another thing which came to my mind was, if there is a possibility to host the Automator on the cloud and have a browser interface where a user can type in their email and password and then on a separate server or something it’ll run the automation completing their daily/bonus goal.

**Comment by Gloryness** [comment]
> Another thing which came to my mind was, if there is a possibility to host the Automator on the cloud and have a browser interface where a user can type in their email and password and then on a separate server or something it’ll run the automation completing their daily/bonus goal.
> On 19 Apr 2021, 5:07 PM +0100, Gloryness ***@***.***>, wrote:
> > so do you mean something like running it without needing to open up the software?
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Damn, that does sound pretty cool indeed but i'm not sure how to do something like that
