### ISSUE TITLE
update unavailable yet

### ISSUE THREAD

**Issue by BubblemintEDM** [Gloryness/tassomai-automation#46]
It tells me to update the application but I can't find the github release.

Also the ability to save your preferences would be cool :D

**Comment by Gloryness** [comment]
SORRY ABOUT THAT! i forgot to release it, it was 3am when i updated it lol
[click here for update link](https://github.com/Gloryness/tassomai-automation/releases/tag/v2021.04.19)

**Comment by Gloryness** [comment]
and yess i might add something like that in the future :D
