### ISSUE TITLE
Tassomai Automation v2021.04.19 Update

### ISSUE THREAD

**Issue by StrikingVengeance** [Gloryness/tassomai-automation#47]
Hey I was wandering when the Tassomai Automation v2021.04.19 Update is coming out?
![Screenshot 2021-04-19 165130](https://user-images.githubusercontent.com/82826545/115265852-89a8ad80-a12f-11eb-9038-6f4ea4e65218.jpg)

**Comment by Gloryness** [comment]
sorry about that (forgot to release it)
only JUST released it! [Click here for the link](https://github.com/Gloryness/tassomai-automation/releases/tag/v2021.04.19)
