### ISSUE TITLE
Have a Accuracy slider or a time grinder.

### ISSUE THREAD

**Issue by BobKarma** [Gloryness/tassomai-automation#5]
Accuracy slider:
                          Have a slider that has a slider from 0% to 100% to allow the user to get the desired accuracy. It may be difficult to implement tho.
Time grinder:
                          You can change how much time to spend on a question, eg i want to spend 10 sec per question or 2 minutes per quiz

**Comment by Gloryness** [comment]
Thanks for the suggestions!
