### ISSUE TITLE
Keeps finishing before its even done a question

### ISSUE THREAD

**Issue by Mozart189** [Gloryness/tassomai-automation#51]
Every time i try and start it im met with "Quiz 1" and then it says completed
im getting this error:

ERROR:root:Traceback (most recent call last):
  File "base\https\session.py", line 142, in start
  File "base\https\tassomai.py", line 48, in extract_quiz_data
IndexError: list index out of range

and 

QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)

**Comment by Gloryness** [comment]
I literally just tested it now myself and it all works so i'm kinda confused

**Comment by Mozart189** [comment]
im not sure because it seems like its specific to my account
i tried it on my friends account on the same pc as i do mine and it worked fine consistently but whenever i try mine im met with the same error about line 142 in session.py and line 48 in tassomai.py

**Comment by Gloryness** [comment]
ooh well can u see if there is any difference between the 2 accounts?
