### ISSUE TITLE
Tassomai anticheat??

### ISSUE THREAD

**Issue by Pengu1n11** [Gloryness/tassomai-automation#55]
After 2-3 days all the progress i did on the bot dissapears and only the answers i manualy did pops up 
![image](https://user-images.githubusercontent.com/51524858/133124847-7a6fcbe8-4cc3-4d88-919e-a17240dce463.png)

**Comment by Gloryness** [comment]
Huh.. that's odd. I tested it just now and seems to be showing up just fine on my statistics page.
Try testing around with the delay settings such as making a 5-15 second random delay between each question and see if that makes a difference (other than that I'm not sure)

**Comment by JasonDerulo1259** [comment]
Yeah, as @Gloryness said, it's probably best to add a delay. Even if there is no Anti-Cheat, the statistics can be viewed by admins and teachers. So if theyve seen that you've done 1000 questions in a minute they're probably gonna be a bit suspicious of you lol

**Comment by ProgrammAbelSchool** [comment]
I have the same issue, adding a delay does not work. It's detecting the bot itself and removing any questions answered by it - if you answer questions legitimately on the same day it only counts those.

> 
> 
> Huh.. that's odd. I tested it just now and seems to be showing up just fine on my statistics page.
> Try testing around with the delay settings such as making a 5-15 second random delay between each question and see if that makes a difference (other than that I'm not sure)

The points are removed the next day, so you won't see the issue right away.

**Comment by Gloryness** [comment]
Oh, okay - I will try and compare the 2 processes (doing it legitimately and automating it) and see if there is any sort of solution to prevent this from happening.

> The points are removed the next day, so you won't see the issue right away. Otherwise I have no idea why it isn't happening for you...
I mean - the last 4 days has been fine but on Friday and Saturday I was sure that I did it but it never counted it so I'm pretty sure it did happen to me then (idk why the last 4 days has worked)

**Comment by Pengu1n11** [comment]
I spoke to my science teacher and she emailed tassomai support. They replied and she said that Tassomai have been reprogramming their website to flag and remove suspicious behaviour.

**Comment by Gloryness** [comment]
> 
> 
> I spoke to my science teacher and she emailed tassomai support. They replied and she said that Tassomai have been reprogramming their website to flag and remove suspicious behaviour.

Ah - not much I can do though because I'm clueless on how to workaround it.

**Comment by Gloryness** [comment]
I don't have any solution to this - however I'm working on adding a "workaround" to the problem.
