### ISSUE TITLE
Tassomai detecting bots?

### ISSUE THREAD

**Issue by BIGboyal** [Gloryness/tassomai-automation#56]
HI, I used the program with a 5-6 second delay and my number of questions completed was cleared. Is tassomai now detecting the bot somehow?
thanks

**Comment by Gloryness** [comment]
Yeah, it is.
See https://github.com/Gloryness/tassomai-automation/issues/55

**Comment by BIGboyal** [comment]
@Gloryness I have tested it and it seems you have to have a long delay in between questions to not be detected. I did a 10-12 second delay and it hasten removed my points in over 24hrs so I think it still can be used.

**Comment by Gloryness** [comment]
> 
> 
> @Gloryness I have tested it and it seems you have to have a long delay in between questions to not be detected. I did a 10-12 second delay and it hasten removed my points in over 24hrs so I think it still can be used.

I did mine at a 15-25 second delay. It took 3 days for the 3-4 days worth of progress to just all of a sudden vanish sooo yeah it'll work but eventually there's a risk of it being erased.
