### ISSUE TITLE
New version v2021.09.25?

### ISSUE THREAD

**Issue by RxndomDude** [Gloryness/tassomai-automation#57]
Hey the Automator told me to update it
![tassomai updtae](https://user-images.githubusercontent.com/90008808/134766550-e81575ff-fff2-43a0-8161-2a7bdaddcd89.jpg)

**Comment by Gloryness** [comment]
Correct! It automatically does this and this is normal. Just download Tassomai Automation.zip from the latest release from https://github.com/Gloryness/tassomai-automation/releases. (you will have to remove the original Tassomai Automation.exe file from your computer manually though as there is no uninstall feature)
