### ISSUE TITLE
Please add a delay system

### ISSUE THREAD

**Issue by BubblemintEDM** [Gloryness/tassomai-automation#6]
So Tassomai keeps a record of when you have completed the question and if the teacher sees that you've finished over 30 questions in under 1 minute that's very suspicious. Would it be possible to add an option to add a random 1-5 second delay per question so it seems less suspicious?

**Comment by Gloryness** [comment]
Good idea. Working on it right now >:D

**Comment by BubblemintEDM** [comment]
I forgot to mention, would it be possible to have the ability to choose the amount of delay? (maybe the ability to set a lower bound and upper bound via a 2 text boxes or a slider)

**Comment by Gloryness** [comment]
yeah I'm sure I could implement that
