### ISSUE TITLE
Won't update stats

### ISSUE THREAD

**Issue by Sp3ckle** [Gloryness/tassomai-automation#66]
I have come to realised that recently the tassomai automation program has not actually have the statistics and daily goals completed and recorded but however finishes the daily goal for you therefore it being useless. I dont know what happened to the program but daily goals arent being recorded

**Comment by Gloryness** [comment]
Yep ik. It's an ongoing issue already if you didn't notice and is still in need of a solution
in the meantime, the lookup tool is a perfect workaround
