### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by ahmedhakim786** [Gloryness/tassomai-automation#67]
Hello,

On my mac whenever I try to run the code in terminal it says that "-bash: $: command not found" so if you could possibly find a fix for this I will be very grateful. FYI I am on MacOS 12.0.1 on a MacBook Air

**Comment by Gloryness** [comment]
what command are you running that produces that error?
and are you using the source code or executable file?

**Comment by ahmedhakim786** [comment]
Whenever I type '$ bash permissions.sh' it says '-bash: $: command not found' and whenever I try opening Tassomai Automation it comes up as a document.

**Comment by Gloryness** [comment]
Oooh you're not meant to include the `$ `, only `bash permissions.sh`
and i don't know what you mean by "a document", like a text document or?

**Comment by ahmedhakim786** [comment]
yes it comes up as a text document and whenever I type `bash permissions.sh` it says "No such file or directory"

**Comment by Gloryness** [comment]
edit `permissions.sh` and then ctrl+a and delete to remove everything and then paste in the following to replace it:
```bash
chmod u+wrx "./Tassomai Automation"
chmod u+wrx "./github_db"
```

**Comment by ahmedhakim786** [comment]
ive tried that but still nothing seems to be working

**Comment by Gloryness** [comment]
do you mind joining the discord so we can try to fix this? its difficult here with the long response times
https://discord.gg/M2Jnp8aQfp
