### ISSUE TITLE
Subjects Box

### ISSUE THREAD

**Issue by Xcc14** [Gloryness/tassomai-automation#68]
Everytime I try to run the automation it opens a box with the word Subjects then does [nothing.]

**Comment by Gloryness** [comment]
what subjects do you have?

**Comment by Gloryness** [comment]
if they are custom subjects, i'm aware of it and they will be implemented in the next update

**Comment by Xcc14** [comment]
> what subjects do you have?

Eng,Sci,Math,Music tech,Computer Sci,Geo

**Comment by Gloryness** [comment]
tassomai-automation only supports English, Science and Maths rn
custom subjects will be added later on
