### ISSUE TITLE
new issue with the delay option when put on question mode

### ISSUE THREAD

**Issue by BobKarma** [Gloryness/tassomai-automation#7]
dk why but when you put the delay option on the question  it only dose one question and teats it. 
![image](https://user-images.githubusercontent.com/76540780/103161775-a024a500-47de-11eb-9257-31ed6d31ed14.png)

Good luck man. Love your work.

**Comment by BobKarma** [comment]
delay quiz option works tho.  And it will be cool if you can have both options activated at ones.

Nice software man keep going.

**Comment by Gloryness** [comment]
thanks >:D
i've found the error and am currently working on a fix !

**Comment by BobKarma** [comment]
cool good luck man
